version: "3"
networks:
  shared:
    driver: bridge

services:
  scraper-app:
    build: 
      context: ./web_scraper
      dockerfile: Dockerfile
    depends_on:
        - scraper-mongo
    ports:
        - "80:80"
    networks:
    - shared
  scraper-mongo:
    image: mongodb/mongodb-community-server:latest
    ports:
        - "27017:27017"
    networks:
    - shared
